---
apiVersion: v1
kind: Service
metadata:
  name: mylab-cafe-app
  labels:
    app: cafe-app
spec:
  type: LoadBalancer
  selector:
    app: cafe-app
  ports:
    - name: http
      port: 80
      targetPort: 80





















---
apiVersion: apps/v1
Kind: 
metadata:
  name: mylab-cafe-app
  labels:
    app: cafe-app
spec:
  selector:
    app: cafe-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
