apiVersion: v1
kind: Pod
metadata: 
  name: ed-nginx
spec:
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}
